### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [Bookingjini-Labs/bookingjini-icons#19] opened 2023-05-20 04:26 UTC
I would like to improve the readme file of this project. Making it expressive for the users.

**Comment by harshsingh32** [comment] 2023-05-20 04:26
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by AshutoshDash1999** [comment] 2023-05-20 13:55
@harshsingh32 hi thanks for contributing. Can you please share what exactly you want to improve?

**Comment by harshsingh32** [comment] 2023-05-20 14:01
I would like to improve the readme file by using catchy phrases and expressive information to engage the users so that they can contribute to the project and they can collaborate with open source. I would be using colourful symbols and catchy slogans so the users can contribute to the project.

**Comment by bookingjini** [comment] 2023-05-20 14:21
> I would like to improve the readme file by using catchy phrases and expressive information to engage the users so that they can contribute to the project and they can collaborate with open source. I would be using colourful symbols and catchy slogans so the users can contribute to the project.

Thank you @harshsingh32 for your prompt response. Feel free to proceed with your contribution and do provide a screenshot during the pull request.

**Comment by mahekkg** [comment] 2023-05-21 05:33
Hey @AshutoshDash1999 

As an open-source contributor of GSSoC'23, I noticed that the README file could benefit from some improvements. It would be great to enhance the clarity and completeness of the documentation to help new developers understand the project better. Suggestions for improvement include:
- Providing a brief project overview and its purpose
 - Explaining how to set up and run the project locally
 - Listing any dependencies or requirements
 - Documenting the project structure and key components
 - Providing instructions for contributing and guidelines for pull requests
 - Including any relevant badges, such as build status or code coverage

These improvements will make it easier for contributors to understand and get started with the project. I would be happy to contribute my time and expertise to enhance the README file as part of my GSSoC'23 contribution. Please let me know if I can be of assistance. Thank you!

**Comment by AshutoshDash1999** [comment] 2023-05-21 06:07
hey @mahekkg, the issue is already assigned. Will reassign it to you if the current assignee ghosts or the PR is not satisfactory,

**Comment by mahekkg** [comment] 2023-05-21 07:56
@AshutoshDash1999  Sure, looking forward to it.

**Closed as completed** 2023-06-23 05:38 UTC
Labels: documentation, gssoc23
